### ISSUE TITLE
Publish on extensions.gnome.org

### ISSUE THREAD

**Issue by noirbizarre** [repsac-by/gnome-shell-extension-quake-mode#1]
Thanks for this extension !!
It works after a restart.

Is it possible to publish it on extensions.gnome.org so it benefit from semi-automatic upgrades ?

**Comment by repsac-by** [comment]
I'm thinking about publishing, but later.
There are some implementation features that need to be improved slightly.

**Comment by repsac-by** [comment]
https://extensions.gnome.org/extension/1411/quake-mode/
