### ISSUE TITLE
Timeout with custom desktop files?

### ISSUE THREAD

**Issue by ProfRon** [repsac-by/gnome-shell-extension-quake-mode#10]

**Comment by repsac-by** [comment]
The desktop file name: `com.gexperts.Tilix.CustomGroup.desktop`
```ini
[Desktop Entry]
Name=Tilix Custom
Exec=tilix --group=CustomGroup --profile=Profile2
Type=Application
StartupNotify=true
Icon=com.gexperts.Tilix
DBusActivatable=false
Actions=new-window

[Desktop Action new-window]
Name=New Window
Exec=tilix --new-process --group=CustomGroup --profile=Profile2

```

**Comment by ProfRon** [comment]
Thanks!
I can confirm that this file works for me -- almost. 

I had to replace "--profile=[profile-name]" with "-p [profile-name]". No idea why that was necessary, but with the long version, I still get a time-out, and with the short version it works.

For the sake of completeness, I noticed you changed two things -- the DBusActivatable setting and the new "--group" command line argument -- and I can confirm you need both.  I was a little nervous about the group argument, since it is documented only in "tilix --help" (not in the man page) and "tilix --help" says that it is "Experimental, not recommended". But I'm willing to live with it -- for the time being at least.

Side note: Now that I can choose my own profile, I tried opening a stored session, i.e. using the "--session=[json-file-name]" command line switch, but that doesn't work. It doesn't time out, but tilix is invisible.  Still, that's a story for another day (or perhaps, a different "issue").

P.S. In case it matters, I'm using the version of your extension from the Gnome Extensions page (not straight from git), and tilix version 1.8.9 (VTE version: 0.54, GTK Version: 3.24.4), under Arch Linux.
