### ISSUE TITLE
[PRs] Fixes for upcomming Gnome and improved installation instructions

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [repsac-by/gnome-shell-extension-quake-mode#13]
I made two fixes in the GitLab fork which might be interesting:
> Fixed Tweener in coming Gnome 3.37 
https://gitlab.com/JasMich.de/gnome-shell-extension-quake-mode/-/tree/gnome-3-37

and

> Fixed instillation instructions
https://gitlab.com/JasMich.de/gnome-shell-extension-quake-mode/-/tree/readme

**Comment by repsac-by** [comment]
thanks
