### ISSUE TITLE
Missing tweener in gnome 3.38

### ISSUE THREAD

**Issue by sheepy9** [repsac-by/gnome-shell-extension-quake-mode#18]
Hi, 
I love the extension, I've used it as part of my day to day workflow. I even modified a version to create a sidebar.
Gnome 3.38 breaks the extension due to missing JS module tweener.
In the gnome extensions manager I get the following error for the extension:

> Error: No JS module 'tweener' found in search path

And some other shell extensions (like pomodoro for example) show the same error.
Is there a quick fix or workaround for this issue?
(Tested on 2 Debian sid PCs)

**Comment by repsac-by** [comment]
Thank you. Tweener replaced with clutter animations.

**Comment by sheepy9** [comment]
After latest commit, extension works well with gnome 3.38.
Thanks guys. You're awesome!
