### ISSUE TITLE
Gnome 40

### ISSUE THREAD

**Issue by drakkar1969** [repsac-by/gnome-shell-extension-quake-mode#24]
Would it be possible to add GNOME 40 to the `metadata.json` file?

Extension appears to work fine in GNOME 40, but can only be enabled if version validation is disabled

Thanks for the great extension btw, life-saver with tilix

**Comment by MuhammedTaha02** [comment]
I am using the plugin. But I can't adjust. It would be nice if you can update for Gnome40.

![image](https://user-images.githubusercontent.com/62564400/113993633-aa652f00-9822-11eb-9b5d-4cccfeacea5b.png)

**Comment by holzi91** [comment]
Not working for me. I'm getting the tray icon for this extension but I can't get tilix to launch through it.

**Comment by MuhammedTaha02** [comment]
> Not working for me. I'm getting the tray icon for this extension but I can't get tilix to launch through it.

1) Install this extension from the gnome-extension store
2) Make a folder on ~/.local/share/ and make folder name "glib-2.0"
3) Make a folder on ~/.local/share/glib-2.0/ and make folder name "schemas"
4) Go to ~/.local/share/gnome-shell/extensions/quake-mode. And copy the two files located inside the schemas folder to the path ~/.local/share/glib-2.0/schemas
5) Install dconf-editor and open
6) Go to /com/github/respac-by/quake-mode and make the setting you want here.

For example
![image](https://user-images.githubusercontent.com/62564400/114038136-9be13c80-984f-11eb-83ec-5ee980ed80d8.png)
