### ISSUE TITLE
Publish version compatible with Gnome 40

### ISSUE THREAD

**Issue by noirbizarre** [repsac-by/gnome-shell-extension-quake-mode#29]
Hello 👋🏼 

Can you publish the latest version, ie. `master`/`HEAD` containing the Gnome 40 compatibility fixes on https://extensions.gnome.org/?
https://extensions.gnome.org/extension/1411/quake-mode/ is still showing the previous versions and people using Gnome 40 for the last 3 weeks can't access your extension (which is great by the way) anymore.

**Comment by repsac-by** [comment]
Thank you, I sent the extension for review. It remains to wait a little for the publication.

**Comment by repsac-by** [comment]
published

**Comment by noirbizarre** [comment]
Thank you very much !!!!! 🙏🏼
