### ISSUE TITLE
Hide app window 

### ISSUE THREAD

**Issue by Nasreddine** [repsac-by/gnome-shell-extension-quake-mode#40]
I'm using the extension to run terminal. 
I do not want to see the terminal window with list of opened apps. 
Is there a solution for that ?

**Comment by eaon** [comment]
https://extensions.gnome.org/extension/2639/hide-minimized/ is an option, but that's assuming you don't minimize windows otherwise.

**Comment by Nasreddine** [comment]
thank you for the extension, however, it is not practical since it affects all apps.
