### ISSUE TITLE
Not all keys could be set as shortcut

### ISSUE THREAD

**Issue by skatkov** [repsac-by/gnome-shell-extension-quake-mode#41]
Would be amazing, if I could set 'CapsLock' key as a shortcut for quake-mode. It's a key I never use on my keyboard, but unfortunately, it's impossible to set as a shortcut.

**Comment by eaon** [comment]
For that you have to remap CapsLock to act as another key, for example `Menu`. Gnome Tweaks' Additional Layout Options in the Keyboard & Mouse tab lets you do that.

**Comment by skatkov** [comment]
@eaon thanks for the tip. It actually worked!
