### ISSUE TITLE
Gnome 42 support?

### ISSUE THREAD

**Issue by RafalSkolasinski** [repsac-by/gnome-shell-extension-quake-mode#45]
Is there a timeline when support for Gnome 42 (now available e.g. in ubuntu 22.04 beta) will come?

**Comment by RafalSkolasinski** [comment]
Thanks, that worked. I just had to log out and in again. 

However there seem to be small issues:
- it is opening on wrong monitor
- the Application tab in extension settings does not open (hangs, and can only close settings)

**Comment by repsac-by** [comment]
done
