### ISSUE TITLE
Hide from Gnome dock and dash

### ISSUE THREAD

**Issue by evoerman** [repsac-by/gnome-shell-extension-quake-mode#5]
Great extension to fix the Wayland support for Tilix. The builtin Tilix quake mode however hides the app from the Gnome dock and dash. Any possibilities to do it with this extension as well?

**Comment by repsac-by** [comment]
Unfortunately, I have not found the right way yet. All I could do was more like a hack. I will consider your ideas.

To hide, we need to set the skip_taskbar property for MetaWindow, but I do not know how to access it.

**Comment by repsac-by** [comment]
> This might require some patches to tilix.

@smurfendrek123, That's possible. I'll try.

**Comment by minghong** [comment]
Tilix quake mode is hide by dock 
my environment:
- utuntu 18.04
- laptop and a outer monitor
- join diplays, and set outer monitor as primary display.

But if built-in display is used as primary display, quake mode works fine in both two diplays

**Comment by amitanilkulkarni** [comment]
I managed to kind of work around this issue by using [Hide Minimized](https://extensions.gnome.org/extension/2639/hide-minimized/?c=60065) extension.

Now the terminal doesn't show up in overview mode when retracted.

(Well, along with other minimized apps, but who minimizes things in Gnome anyway)

**Comment by Svadkos** [comment]
> I managed to kind of work around this issue by using [Hide Minimized](https://extensions.gnome.org/extension/2639/hide-minimized/?c=60065) extension.

@repsac-by wouldn't it be possible to use the same mechanism, but only for the app in quake mode?

**Comment by amitanilkulkarni** [comment]
@Svadkos - I tried what you're suggesting, and it hides only the app in quake mode.

There are two caveats though. **All** instances of quake-mode app will be hidden, and this only works for GTK-based terminal emulators (which should be fine for a gnome-shell extension). For the former one, I don't know a way to distinguish quake-mode Tilix instance from other Tilix instances.

I'll try playing around with it further and submit a merge request if it seems alright to @repsac-by .
