### ISSUE TITLE
Error message after installation

### ISSUE THREAD

**Issue by Venemo** [repsac-by/gnome-shell-extension-quake-mode#6]
After running `gnome-shell-extension-prefs quake-mode@repsac-by.github.com` I get an error: "There was an error loading the preferences dialog for quake-mode".

```
Error: Argument 'icon' (type interface) may not be null

Stack trace:
  buildRow@/home/Timur/.local/share/gnome-shell/extensions/quake-mode@repsac-by.github.com/prefs.js:134:18
  _init/<@/home/Timur/.local/share/gnome-shell/extensions/quake-mode@repsac-by.github.com/prefs.js:125:30
  _init@/home/Timur/.local/share/gnome-shell/extensions/quake-mode@repsac-by.github.com/prefs.js:123:3
  _init@/home/Timur/.local/share/gnome-shell/extensions/quake-mode@repsac-by.github.com/prefs.js:207:20
  buildPrefsWidget@/home/Timur/.local/share/gnome-shell/extensions/quake-mode@repsac-by.github.com/prefs.js:213:17
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
  
```

**Comment by ProfRon** [comment]
By the way, I'm having this problem too. Using Archlinux, Gnome Shell 3.28, Wayland... Can I tell you anything else? 

Javascript is really not my language, but if you look at "prefs.js:134:18", it looks like it is building a table (probably for selecting apps to put in guake mode?) and calls for an icon for each row  (i.e. each app?), and gets messed up if some times there is no icon?!?  Take that with a grain of salt. I checked whether I could find any apps without icons, and find none in the "overview", but that's not really saying much, is it? (It might be clever enough not to show me those with no icons, if there are in fact any?).

**Comment by ProfRon** [comment]
Fixed! Thanks!
