### ISSUE TITLE
Support for Gnome 44

### ISSUE THREAD

**Issue by petre2dor** [repsac-by/gnome-shell-extension-quake-mode#69]
Hi, 

With the release of Fedora 38, Gnome 44 is also available.
Can someone please update this extensions to support Gnome 44?

Thank you for your efforts :)

**Comment by petre2dor** [comment]
I updated `metadata.json` and added "44" and it seems to working just fain

**Comment by petre2dor** [comment]
I just noticed that support was already added in [this commit](https://extensions.gnome.org/extension/1411/quake-mode/), but it's not available yet here: https://extensions.gnome.org/extension/1411/quake-mode/
Is there a need to make a release or update the version number?

**Comment by huyhoang160593** [comment]
please add support for gnome 44, i really need this to use for my new fedora 38 :(
