### ISSUE TITLE
Request for the support of multiple applications on multiple keyboard shortcuts.

### ISSUE THREAD

**Issue by kjschanney** [repsac-by/gnome-shell-extension-quake-mode#7]
Hi,
Great extension, been looking for a drop-down window for emacs (not in terminal). Is it possible to add the support for multiple applications? Right now I am using emacs on F1, it would be great if I can also bind Firefox on F12, Mathematica on F9 and Mendeley Desktop on F8 :-)

again thanks for the extension.

**Comment by jediaxe** [comment]
quake-mode is an excellent extension. its just not complete without this feature, (multiple applications with multiple shortcuts)

Adding an option for drop-down position (Top, Bottom, left, right) for each application would be great too :)

**Comment by bjames88** [comment]
I was just thinking how awesome it would be if this extension supported multiple apps.
