### ISSUE TITLE
GNOME 45 breaks extension compatibility

### ISSUE THREAD

**Issue by Henry78** [repsac-by/gnome-shell-extension-quake-mode#75]
https://linuxiac.com/gnome-45-breaks-extensions-compatibility/

Extensions that target older GNOME versions will not work in GNOME 45. Likewise, extensions that are adapted to work with GNOME 45 will not work in older versions.

**Comment by diegodario88** [comment]
I've created a port for this extension, which you can check out at this [link](https://extensions.gnome.org/extension/6307/quake-terminal/), although it doesn't have all the features.

**Comment by piousdeer** [comment]
I have made a direct port with minimal changes required to get it working on GNOME 45. As such, all of quake-mode's features and quirks have been preserved. On top of that, I've also added a "gap" setting where you can specify the terminal's distance from the edges of the screen. You can find my fork [here](https://github.com/piousdeer/gnome-shell-extension-quake-mode).

I will release it as a separate extension on extensions.gnome.org if I end up making more substantial changes, but for now a build can be found in the [releases tab](https://github.com/piousdeer/gnome-shell-extension-quake-mode/releases).

**Comment by shilangyu** [comment]
Hey people that have managed to port the extension to support gnome 45, would you consider opening a PR to this repo?

**Comment by piousdeer** [comment]
I initially assumed the author was inactive, but perhaps that was incorrect, so I'll open a PR
