### ISSUE TITLE
Extension only creates invisible window on Gnome 3.30

### ISSUE THREAD

**Issue by alraban** [repsac-by/gnome-shell-extension-quake-mode#8]
The iusse appears after upgrading to Gnome 3.30 (running wayland), using the extension with tilix.  The extension appears to run, but when pressing the accelerator key or clicking the icon, there appears to be no effect.  However, going to the activities overview or alt-tabbing reveals that the extension did create a tilix window, but that window is invisible/hidden.  The invisible window also appears to have Tilix's default launch geometry rather than the geometry configured in the extension.  Let me know if I can provide any more info to help troubleshoot.

Also, while I'm here, I wanted to say "thank you" for your very helpful extension.  I've been using it happily on Gnome-shell 3.28 for a few months!

**Comment by ProfRon** [comment]
I'm seeing this problem too.  Exactly as described above.

**Comment by repsac-by** [comment]
I uploaded v2 to extensions.gnome.org
But I do not know how long the review will take place.
The last time the publication took several months.

**Comment by alraban** [comment]
Thanks for the quick response.  I updated via the AUR, and all is working perfectly now.
